package rcsas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Yu Jue Cheon
 */
public class AdminSportCenterEdit extends javax.swing.JFrame {
    private String dateTime;
    private boolean registeredName;
    private String sportCenter;
    private String beforeEdited;
    /**
     * Creates new form AdminSportCenterEdit
     */
    public AdminSportCenterEdit() {
        initComponents();
        addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                RCSAS.adminSportCenter.setEnabled(true);
            }
        });
    }
    
    public void setTextField(){
        for(int i=0;i<RCSAS.allSportCenter.size();i++){
            SportCenter sc = RCSAS.allSportCenter.get(i);
            if(RCSAS.adminSportCenter.selectedSportCenterID.equals(sc.getID())){
                lblID.setText(sc.getID());
                lblDateCreated.setText(sc.getDateCreated());
                txtSportCenterName.setText(sc.getName());
                txtAddress.setText(sc.getAddress());
                txtPhone.setText(sc.getPhoneNo());
                txtEmail.setText(sc.getEmail());
                txtOpenTime.setText(sc.getOpenTime());
                txtCloseTime.setText(sc.getCloseTime());
                
            }
        }
        beforeEdited = txtSportCenterName.getText();
    }
    //Sport Center Edit
    public void UpdateScheduleFile1(){
        for(int i=0; i<RCSAS.allSchedule.size();i++){
            Schedule ss = RCSAS.allSchedule.get(i);
            if(ss.getSportCenterName().equals(beforeEdited)) {
                ss.setSportCenterName(sportCenter);
            }
        }
        RCSAS.adminSchedule.updateTxtFile();
    }
    //Sport Center Edit
    public void UpdateCoachFile1(){
        for(int i=0; i<RCSAS.allCoach.size();i++){
            Coach c = RCSAS.allCoach.get(i);
            if(c.getSportCenterName().equals(beforeEdited)) {
                c.setSportCenterName(sportCenter);
            }
        }
        RCSAS.adminCoach.UpdateCoachFile();
    }
    //Sport Center Edit
    public void UpdateAdminFile1(){
        for(int i=0; i<RCSAS.allAdmin.size();i++){
            Admin a = RCSAS.allAdmin.get(i);
            if(a.getSportCenterName().equals(beforeEdited)) {
                a.setSportCenterName(sportCenter);
            }
        }
        RCSAS.admin.UpdateAdminFile();
    }
    //Sport Center Edit
    public void UpdateSportFile1(){
        for(int i=0; i<RCSAS.allSport.size();i++){
            Sport s = RCSAS.allSport.get(i);
            if(s.getSportCenterName().equals(beforeEdited)) {
                s.setSportCenterName(sportCenter);
            }
        }
        RCSAS.adminSport.UpdateSportFile();
    }
    //Sport Center Edit
    public void UpdateLocationFile1(){
        for(int i=0; i<RCSAS.allLocation.size();i++){
            Location l = RCSAS.allLocation.get(i);
            if(l.getSportCenterName().equals(beforeEdited)) {
                l.setSportCenterName(sportCenter);
            }
        }
        RCSAS.adminSportCenter.UpdateSportLocationFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSportCenterName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtOpenTime = new javax.swing.JTextField();
        txtCloseTime = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        lblDateCreated = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(172, 3, 24));
        jPanel3.setPreferredSize(new java.awt.Dimension(574, 85));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Real Champions Sport Academy ");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rcsas/images/logo.png"))); // NOI18N
        jLabel6.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDone.setBackground(new java.awt.Color(172, 3, 24));
        btnDone.setForeground(new java.awt.Color(255, 255, 255));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblID.setText("SP002");
        lblID.setEnabled(false);

        jLabel24.setText("Sport Center ID :");

        jLabel27.setText("Sport Center Name :");

        jLabel9.setText("Address :");

        jLabel10.setText("Email :");

        jLabel11.setText("Phone :");

        jLabel12.setText("Open Time :");

        jLabel13.setText("Close Time :");

        jLabel25.setText("Date Created :");

        lblDateCreated.setText("SP002");
        lblDateCreated.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("07:00 - 21:00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("09:01 - 23:59");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblDateCreated)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress)
                            .addComponent(txtEmail)
                            .addComponent(txtOpenTime)
                            .addComponent(txtCloseTime)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSportCenterName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblDateCreated))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtSportCenterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtOpenTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCloseTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(17, 17, 17))
        );

        jScrollPane1.setViewportView(jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDone)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDone)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        dateTime = DateTime.DateTime();
        String address = txtAddress.getText();
        String phone = txtPhone.getText();
        String email = txtEmail.getText();
        String openTime = txtOpenTime.getText();
        String closeTime = txtCloseTime.getText();
        
        
        if( (address == "") || (phone == "") || (email == "") || (txtSportCenterName.getText() =="") || 
                (openTime == "") || (closeTime == "")){
            JOptionPane.showMessageDialog(null,"Empty input!","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            sportCenter = RCSAS.validation.CapitalizeLetter(txtSportCenterName.getText());
            try{
                //Sport center name validation
                for(int i=0; i < RCSAS.allSportCenter.size(); i++){
                    SportCenter sc = RCSAS.allSportCenter.get(i);
                    //if username no edit his username
                    if(RCSAS.adminSportCenter.selectedSportCenterID.equals(sc.getID())){ 
                        if(sportCenter.equals(sc.getName())){
                            sc.setName(sportCenter);
                        }else{
                            sc.setName(sportCenter);
                        }
                    //does the other registered the username or not
                    }else{ 
                        if(sportCenter.equals(sc.getName())){
                            registeredName = true;
                            throw new Exception();
                        }
                    }
                }
                if( (RCSAS.validation.ValidateOpen(openTime) == false) || 
                        (RCSAS.validation.ValidateName(sportCenter) == false) ||
                        (sportCenter.length() > 50) ||  
                        (RCSAS.validation.ValidateClose(closeTime) == false) ||
                        (RCSAS.validation.ValidatePhoneNo(phone) == false) || 
                        (RCSAS.validation.ValidateEmail(email) == false) ){
                    throw new Exception();
                }else{
                    for(int i=0;i<RCSAS.allSportCenter.size();i++){
                        SportCenter sc = RCSAS.allSportCenter.get(i);
                        if(RCSAS.adminSportCenter.selectedSportCenterID.equals(sc.getID())){
                            sc.setDateModified(dateTime);
                            sc.setAddress(address);
                            sc.setPhoneNo(phone);
                            sc.setEmail(email);
                            sc.setOpenTime(openTime);
                            sc.setCloseTime(closeTime);
                        }
                    }
                    JOptionPane.showMessageDialog(null,"Edit successfully");
                    RCSAS.adminSportCenter.UpdateSportCenterFile();
                    RCSAS.adminSportCenter.setEnabled(true);
                    RCSAS.adminSportCenter.addRowToJTable();  
                    UpdateScheduleFile1();
                    UpdateSportFile1();
                    UpdateCoachFile1();
                    UpdateAdminFile1();
                    UpdateLocationFile1();
                    this.setVisible(false);
                }
                
            }catch(Exception ex){
                if(registeredName){
                    JOptionPane.showMessageDialog(null,"Registered username/name","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(
                            null,
                            "Uhh-ohh\n*Sport center name must <= 50 characters and not contain symbols (except '.' and '/') and digits\""
                            + "\n*Phone (e.g. __-_____ 012-3456789)"
                            + "\n*Email (e.g. __@__.__)"
                            + "\n*Open Time & Close Time in 24HR FORMAT (e.g. HH:MM)"
                            + "\n*Open Time range from 07:00-21:00"
                            + "\n*Close Time range from 09:01-23:59",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSportCenterEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSportCenterEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSportCenterEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSportCenterEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSportCenterEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateCreated;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCloseTime;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOpenTime;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSportCenterName;
    // End of variables declaration//GEN-END:variables
}
